name: Pulse - Daily Summary Bot

on:
  schedule:
    - cron: '30 13 * * *' # Schedules code run every evening at 7:00 PM IST
  workflow_dispatch:

jobs:
  run-pulse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Pulse bot
        env:
          EMAIL_SENDER: "dellaannag04@gmail.com"
          EMAIL_RECEIVER: "dellaannag04@gmail.com"
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          # Exposing the OpenWeatherMap API key token securely to the Python run env
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
        run: python bot.py

      - name: Upload summary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: daily-summary
          path: daily_summary.txt
